"""
TRINITY_M1 — Constants
All constants used across the module. No wall-clock. No randomness.
"""

MODULE_NAME: str = "TRINITY_M1"
MODULE_VERSION: str = "1.0.0"

# Input constraints
MIN_BARS: int = 256

# Trust state thresholds
TRUST_SCORE_TRUSTED: float = 0.75
TRUST_SCORE_WATCH: float = 0.50

# Trust state enum values
TRUST_STATE_TRUSTED: str = "TRUSTED"
TRUST_STATE_WATCH: str = "WATCH"
TRUST_STATE_UNTRUSTED: str = "UNTRUSTED"

# Audit quality enum values
AUDIT_QUALITY_NORMAL: str = "NORMAL"
AUDIT_QUALITY_DEGRADED: str = "DEGRADED"

# Canonicalization
CANONICAL_FLOAT_PRECISION: int = 6
CANONICAL_SORT_KEYS: bool = True
CANONICAL_ALLOW_NAN: bool = False

# Kalman filter defaults
KALMAN_PROCESS_NOISE: float = 1e-5
KALMAN_MEASUREMENT_NOISE: float = 1e-3
KALMAN_INITIAL_COVARIANCE: float = 1.0

# Fourier defaults
FOURIER_TOP_N_COMPONENTS: int = 10

# Deviation thresholds
DEVIATION_HIGH_THRESHOLD: float = 0.05

# Reason codes (mirror from YAML — for internal use only)
RC_INPUT_SCHEMA_INVALID: str = "TRINITY_M1_INPUT_SCHEMA_INVALID"
RC_INPUT_MISSING_FIELD: str = "TRINITY_M1_INPUT_MISSING_FIELD"
RC_INPUT_TYPE_MISMATCH: str = "TRINITY_M1_INPUT_TYPE_MISMATCH"
RC_TIMESTAMP_INVALID: str = "TRINITY_M1_TIMESTAMP_INVALID"
RC_SYMBOL_INVALID: str = "TRINITY_M1_SYMBOL_INVALID"
RC_INSUFFICIENT_BARS: str = "TRINITY_M1_INSUFFICIENT_BARS"
RC_NAN_INF_DETECTED: str = "TRINITY_M1_NAN_INF_DETECTED"
RC_FOURIER_COMPUTE_FAIL: str = "TRINITY_M1_FOURIER_COMPUTE_FAIL"
RC_FOURIER_SPECTRAL_SIGNATURE_INVALID: str = "TRINITY_M1_FOURIER_SPECTRAL_SIGNATURE_INVALID"
RC_KALMAN_INIT_FAIL: str = "TRINITY_M1_KALMAN_INIT_FAIL"
RC_KALMAN_STEP_FAIL: str = "TRINITY_M1_KALMAN_STEP_FAIL"
RC_JACOBIAN_COMPUTE_FAIL: str = "TRINITY_M1_JACOBIAN_COMPUTE_FAIL"
RC_EVIDENCE_LOG_EMPTY: str = "TRINITY_M1_EVIDENCE_LOG_EMPTY"
RC_EVIDENCE_RECORD_INVALID: str = "TRINITY_M1_EVIDENCE_RECORD_INVALID"
RC_PATTERN_DETECT_FAIL: str = "TRINITY_M1_PATTERN_DETECT_FAIL"
RC_AUDIT_DEGRADED: str = "TRINITY_M1_AUDIT_DEGRADED"
RC_TRUST_SCORE_LOW: str = "TRINITY_M1_TRUST_SCORE_LOW"
RC_BROKER_DEVIATION_HIGH: str = "TRINITY_M1_BROKER_DEVIATION_HIGH"
RC_INTERNAL_ERROR: str = "TRINITY_M1_INTERNAL_ERROR"
