"""
AIEL-T Wrapper for Factory A v2.0
==================================

Integrates AIEL-T Framework (4 engines) with Factory A pipeline.

Flow:
1. AIEL-0→3 (Code Gen) → module.zip [G-Score v1.1]
2. AIEL-T (Testing) → G-Score [4 engines] ← THIS FILE
3. Integration → Compat check
4. M8+Stage2+M7 → Authority gates
5. Golden Lib → Final output

This wrapper:
- Runs AIEL-T 4 engines
- Calculates G-Score (AIEL-T version)
- Returns standardized result
- Works with multi-language via adapters
"""
import sys
import os
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

# Import AIEL-T engines
aiel_t_path = Path("/home/claude/AIEL-T Framework  v1.0_pass")
sys.path.insert(0, str(aiel_t_path))

try:
    from AIEL_T_Engine import AIELTEngine
    from Invariants_Engine import InvariantsEngine
    from Pattern_Engine import PatternEngine
    from Contract_Engine import ContractEngine
    from Scenario_Engine import ScenarioEngine
except ImportError as e:
    print(f"Warning: Could not import AIEL-T: {e}")
    # Fallback: Use mock
    AIELTEngine = None


from adapter_registry import AdapterRegistry


class AIELTWrapper:
    """
    AIEL-T Wrapper for Factory A
    
    Runs AIEL-T validation on code generated by AIEL-0→3.
    
    G-Score Formula (AIEL-T):
    G = 0.45×Invariants + 0.15×Patterns + 0.10×Contracts + 0.30×Scenarios
    
    Threshold: G ≥ 0.95
    """
    
    G_SCORE_THRESHOLD = 0.95
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize AIEL-T wrapper
        
        Args:
            config: Configuration dict with paths to specs
        """
        self.config = config or {}
        self.adapter_registry = AdapterRegistry()
        
        # Try to initialize AIEL-T engine
        if AIELTEngine:
            try:
                self.aiel_t_engine = AIELTEngine(config=self.config)
                self.aiel_t_available = True
            except Exception as e:
                print(f"Warning: AIEL-T init failed: {e}")
                self.aiel_t_available = False
        else:
            self.aiel_t_available = False
    
    def validate_module(self, 
                       module_path: Path,
                       runtime_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Validate module using AIEL-T
        
        Args:
            module_path: Path to module directory
            runtime_data: Runtime data for validation
            
        Returns:
            AIEL-T result with G-Score
        """
        timestamp_start = datetime.now()
        
        # Step 1: Run tests via adapter
        test_result = self.adapter_registry.run_tests(module_path)
        
        # Step 2: If AIEL-T available, run full validation
        if self.aiel_t_available and runtime_data:
            try:
                aiel_t_result = self.aiel_t_engine.run(runtime_data)
                g_score = aiel_t_result.get('G_score', 0.0)
                
                return {
                    "format": "AIEL-T-RESULT",
                    "timestamp": datetime.now().isoformat(),
                    "module_path": str(module_path),
                    "g_score": g_score,
                    "threshold": self.G_SCORE_THRESHOLD,
                    "status": "PASS" if g_score >= self.G_SCORE_THRESHOLD else "FAIL",
                    "test_result": test_result,
                    "aiel_t_full": aiel_t_result,
                    "processing_time": (datetime.now() - timestamp_start).total_seconds()
                }
            except Exception as e:
                return self._error_response(module_path, f"AIEL-T execution failed: {e}")
        
        # Fallback: Use test result only
        return self._fallback_validation(module_path, test_result, timestamp_start)
    
    def _fallback_validation(self,
                            module_path: Path,
                            test_result: Dict[str, Any],
                            timestamp_start: datetime) -> Dict[str, Any]:
        """
        Fallback validation using test results only
        
        Simpler G-Score calculation based on test coverage.
        """
        tests_total = test_result.get('tests_total', 0)
        tests_passed = test_result.get('tests_passed', 0)
        
        if tests_total == 0:
            # No tests = fail
            g_score = 0.0
            status = "FAIL"
            reason = "No tests found"
        else:
            # G-Score based on test pass rate
            test_pass_rate = tests_passed / tests_total
            
            # Simple formula (can be enhanced)
            g_score = test_pass_rate
            status = "PASS" if g_score >= self.G_SCORE_THRESHOLD else "FAIL"
            reason = f"Test pass rate: {test_pass_rate:.2%}"
        
        return {
            "format": "AIEL-T-RESULT",
            "timestamp": datetime.now().isoformat(),
            "module_path": str(module_path),
            "g_score": g_score,
            "threshold": self.G_SCORE_THRESHOLD,
            "status": status,
            "reason": reason,
            "test_result": test_result,
            "aiel_t_available": False,
            "processing_time": (datetime.now() - timestamp_start).total_seconds()
        }
    
    def _error_response(self, module_path: Path, error: str) -> Dict[str, Any]:
        """Generate error response"""
        return {
            "format": "AIEL-T-RESULT",
            "timestamp": datetime.now().isoformat(),
            "module_path": str(module_path),
            "status": "ERROR",
            "error": error,
            "g_score": 0.0,
            "threshold": self.G_SCORE_THRESHOLD
        }
    
    def get_report(self, result: Dict[str, Any]) -> str:
        """
        Generate human-readable report
        
        Args:
            result: AIEL-T result
            
        Returns:
            Formatted report
        """
        lines = []
        lines.append("=" * 60)
        lines.append("AIEL-T Validation Report")
        lines.append("=" * 60)
        lines.append(f"Module: {result.get('module_path', 'unknown')}")
        lines.append(f"Timestamp: {result.get('timestamp', 'unknown')}")
        lines.append(f"")
        lines.append(f"G-Score: {result.get('g_score', 0.0):.3f}")
        lines.append(f"Threshold: {result.get('threshold', 0.95):.3f}")
        lines.append(f"Status: {result.get('status', 'UNKNOWN')}")
        
        if 'reason' in result:
            lines.append(f"Reason: {result['reason']}")
        
        # Test results
        test_result = result.get('test_result', {})
        if test_result:
            lines.append(f"")
            lines.append(f"Test Results:")
            lines.append(f"  Language: {test_result.get('toolchain', {}).get('language', 'unknown')}")
            lines.append(f"  Tests Total: {test_result.get('tests_total', 0)}")
            lines.append(f"  Tests Passed: {test_result.get('tests_passed', 0)}")
            lines.append(f"  Status: {test_result.get('status', 'UNKNOWN')}")
        
        # AIEL-T details (if available)
        if 'aiel_t_full' in result:
            aiel_t = result['aiel_t_full']
            lines.append(f"")
            lines.append(f"AIEL-T Engines:")
            
            inv = aiel_t.get('invariants', {})
            if inv:
                lines.append(f"  Invariants: {inv.get('score', 0):.3f} (45%)")
            
            pat = aiel_t.get('patterns', {})
            if pat:
                lines.append(f"  Patterns: {pat.get('score', 0):.3f} (15%)")
            
            con = aiel_t.get('contracts', {})
            if con:
                lines.append(f"  Contracts: {con.get('score', 0):.3f} (10%)")
            
            sce = aiel_t.get('scenarios', {})
            if sce:
                lines.append(f"  Scenarios: {sce.get('score', 0):.3f} (30%)")
        
        lines.append("=" * 60)
        
        return "\n".join(lines)


# Test
if __name__ == '__main__':
    print("AIEL-T Wrapper Test")
    print("=" * 60)
    
    wrapper = AIELTWrapper()
    
    # Test with sample directory
    test_dir = Path("/tmp/test_module")
    test_dir.mkdir(exist_ok=True)
    
    # Create a simple Python test
    (test_dir / "test_sample.py").write_text("""
def test_example():
    assert 1 + 1 == 2

def test_another():
    assert True
""")
    
    (test_dir / "requirements.txt").write_text("pytest\n")
    
    # Run validation
    result = wrapper.validate_module(test_dir)
    
    # Print report
    print(wrapper.get_report(result))
    
    print(f"\n✅ AIEL-T Wrapper Ready!")
    print(f"Available: {wrapper.aiel_t_available}")
