"""canonical_schema.py (AUTO-GENERATED PLACEHOLDER TEMPLATE)

Source of truth: CANONICAL_ENVELOPE_v1.yaml + CANONICAL_FIELDS_CORE_v1.yaml
This file SHOULD be generated by generate_canonical_schema.py.
Do NOT edit manually.

Note:
- This model validates the *envelope shape* and core typed sections.
- Project-specific extensions should live under payload.extensions.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict

# ----------------------------- Core Sections -----------------------------

class Meta(BaseModel):
    model_config = ConfigDict(extra="forbid")
    envelope_version: str
    message_id: str
    determinism_key: str
    producer_module: str
    produced_at_utc: str  # informational only; must not affect deterministic outputs


class Evidence(BaseModel):
    model_config = ConfigDict(extra="forbid")
    evidence_complete: Optional[bool] = None
    veto_signal: Optional[bool] = None
    noise_residual: Optional[List[float]] = None
    trust_score: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    detected_patterns: Optional[List[str]] = None


class Decision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    router_action: Optional[str] = Field(
        default=None,
        description="EXECUTE|HALT|BLOCK|SAFE_MODE|REDUCE_RISK"
    )
    decision_hash: Optional[str] = None
    context_hash_seed: Optional[str] = None


class RiskState(BaseModel):
    model_config = ConfigDict(extra="forbid")
    max_drawdown: Optional[float] = None
    exposure: Optional[float] = None
    kill_switch: Optional[bool] = None
    trust_critical_state: Optional[bool] = None
    hard_broker_safety_limits: Optional[bool] = None


class Stamps(BaseModel):
    model_config = ConfigDict(extra="forbid")
    vip_stamps: Optional[List[str]] = None


class Features(BaseModel):
    model_config = ConfigDict(extra="forbid")
    # Container for canonical 12 keys (project defines key registry)
    features_12: Optional[Dict[str, Any]] = None


class Payload(BaseModel):
    model_config = ConfigDict(extra="forbid")
    context: Optional[Dict[str, Any]] = None
    evidence: Optional[Evidence] = None
    features: Optional[Features] = None
    decision: Optional[Decision] = None
    risk_state: Optional[RiskState] = None
    stamps: Optional[Stamps] = None
    extensions: Optional[Dict[str, Any]] = None


class Envelope(BaseModel):
    """Canonical envelope bus.

    All modules should validate inputs/outputs with this model.
    """
    model_config = ConfigDict(extra="forbid")
    meta: Meta
    payload: Payload
    reason_codes: List[str]
